### ISSUE TITLE
AttributeError: 'list' object has no attribute 'item'

### ISSUE THREAD

**Issue by liyang53719** [pulp-platform/nemo#33]
nemo is a very attractive tool, I am trying to run "mnist_test.py".
But an error was encountered. I use pytorch==1.8.1 pytorch-nemo==0.0.8.
An error occurred in the sentence "model.qd_stage(eps_in=1./255)".
I tried to run this example online ：
"https://colab.research.google.com/drive/1AmcITfN2ELQe07WKQ9szaxq-WSu4hdQb#scrollTo=jTaoBWWSkicx".
I got the same error. May I ask what caused this. What steps can I take to fix this error. Thank you.

error log:
AttributeError                            Traceback (most recent call last)
<ipython-input-14-c4908e965a4a> in <module>()
      1 model = nemo.transform.bn_to_identity(model) # necessary because folding does not physically remove BN layers
----> 2 model.qd_stage(eps_in=1./255)
      3 print(model)
      4 acc = test(model, device, test_loader)
      5 print("\nQuantizedDeployable @ mixed-precision accuracy: %.02f%%" % acc)

2 frames
/usr/local/lib/python3.7/dist-packages/nemo/transf/deploy.py in _qd_stage(self, eps_in, add_input_bias_dict, remove_bias_dict, prune_empty_bn, int_accurate, bn_calibration_fn, bn_calibration_range_factor, **kwargs)
    145             if (m.__class__.__name__ == "PACT_Act"):
    146                 m.precise = True
--> 147     self.set_deployment(eps_in=eps_in, **kwargs) # with initial BN eps
    148     if bn_calibration_fn is not None:
    149         with self.statistics_bn():

/usr/local/lib/python3.7/dist-packages/nemo/transf/deploy.py in _set_deployment_pact(self, eps_in, only_activations, **kwargs)
     77     if not only_activations:
     78         self.eps_in = eps_in
---> 79         self.set_eps_in(eps_in)
     80     for n,m in self.named_modules():
     81         if ((not only_activations and m.__class__.__name__ == "PACT_Conv2d") or \

/usr/local/lib/python3.7/dist-packages/nemo/transf/deploy.py in _set_eps_in_pact(self, eps_in)
    101     for n,m in self.named_modules():
    102         if (m.__class__.__name__ == "PACT_Act"):
--> 103             m.eps_in = torch.tensor(self.get_eps_at(n, eps_in).item(), requires_grad=False)
    104         if (m.__class__.__name__ == "PACT_QuantizedBatchNormNd"):
    105             m.eps_in = torch.tensor(self.get_eps_at(n, eps_in).item(), requires_grad=False)

AttributeError: 'list' object has no attribute 'item'

**Comment by hejleo** [comment]
Hi @liyang53719 , if this works for your code try using:
```
!pip install torch==1.5.0
!pip install torchvision==0.6
```
And everything should work just fine!
Let me know

**Comment by liyang53719** [comment]
Thanks for your reply, in Google's online example, it worked perfectly.
I will do the same on my local server. Expect it to have the same performance.
I will let you know when I make any progress

**Comment by liyang53719** [comment]
Hi @hejleo 

I have to ask again .
When I run this example on the local server, the following error is displayed:

ERROR: Could not find a version that satisfies the requirement torch==1.5.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch==1.5.0
ERROR: Could not find a version that satisfies the requirement torchvision==0.6 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2 .post2, 0.2.2.post3, 0.5.0, 0.9.0, 0.9.1)
ERROR: No matching distribution found for torchvision==0.6

My local server uses windows operating system, and I use conda to install and manage dependent libraries.
From the error message, I infer: There is no "torch=1.5.0" and "torch vision=0.6" in the conda environment.
I want to confirm whether this project can support the latest version (torch=1.8.0)? Or 1.7.1?

thank you for your reply

**Comment by liyang53719** [comment]
Hi @hejleo

I re-built an Ubuntu server. The problem of no torch==1.5.0 and torch vision==0.6 no longer exists.

But I am still interested in the latest Torch version that this project can support.

thank you for your reply

**Comment by computerpolice** [comment]
Hey, is there a work around to this issue that doesn't require installing older versions of torchvision? I use pytorch-nemo>=0.0.7, torch==1.9.0+cu102 and torchvision==0.10.0+cu102. Installing older versions of torchvision is off the table for me as I get persistent errors in essential segments of my code that I can't really play around with.
