### ISSUE TITLE
About torch version！

### ISSUE THREAD

**Issue by ChenMathilda** [pulp-platform/nemo#37]
Hi,
when I try to quantize my module, I met this mistake:
loaded checkpoint on cuda
Failed to find the [state_dict] inside the checkpoint. I will try to open it as a checkpoint.
Test: 100%|██████████████████████████████████████████████████████████████| 215/215 [00:04<00:00, 50.50it/s, mse=0, acc=0.669]
Full precision MSE: 0.0000 , Acc: 0.6686, Model size: 1253.00kB
/home/../torch/onnx/symbolic_helper.py:443: UserWarning: ONNX export mode is set to inference mode, but operator batch_norm is set to inference mode. The model will be exported in inference, as specified by the export mode.
  warnings.warn("ONNX export mode is set to " + training_mode +
Test: 100%|██████████████████████████████████████████████████████████████| 215/215 [00:04<00:00, 49.91it/s, mse=0, acc=0.669]
FakeQuantized MSE: 0.0000 , Acc: 0.6686, Model size: 278.00kB
[nemo-graph] Warning: bn1 is not a module name
Traceback (most recent call last):
  File "/home/../pulp-dronet-v2/nemo-dory/quantize.py", line 319, in <module>
    model_q.qd_stage(eps_in=1./255)  # eps_in is the input quantum, and must be set by the user
  File "/home/Mathilda/anaconda3/envs/pulp-dronet-v2/lib/python3.8/site-packages/nemo/transf/deploy.py", line 147, in _qd_stage
    self.set_deployment(eps_in=eps_in, **kwargs) # with initial BN eps
  File "/home/Mathilda/anaconda3/envs/pulp-dronet-v2/lib/python3.8/site-packages/nemo/transf/deploy.py", line 79, in _set_deployment_pact
    self.set_eps_in(eps_in)
  File "/home/Mathilda/anaconda3/envs/pulp-dronet-v2/lib/python3.8/site-packages/nemo/transf/deploy.py", line 105, in _set_eps_in_pact
    m.eps_in = torch.tensor(self.get_eps_at(n, eps_in).item(), requires_grad=False)
**AttributeError: 'NoneType' object has no attribute 'item'**

And I notice that  this was because my wrong torch version, so I changed my torch version to torch=1.5.0, torchvision=0.6.0. After doing this, an error will be reported that the computing power of my GPU is 8.6, while the current computing power supported by pytorch is 7.5.

So I want to ask whether nemo supports a latest version of pytorch?

**Comment by LorenzoLamberti94** [comment]
Hi Mathilda,
Nemo provides regression tests only up to pytorch 1.5, therefore it does not guarantee compatibility with the most recent versions of pytorch yet.

As a general tip, I also suggest to install NEMO directly from git (instead of pip), so you can get all the most recent updates

Best, Lorenzo

**Comment by ChenMathilda** [comment]
> Hi Mathilda, Nemo provides regression tests only up to pytorch 1.5, therefore it does not guarantee compatibility with the most recent versions of pytorch yet.
> 
> As a general tip, I also suggest to install NEMO directly from git (instead of pip), so you can get all the most recent updates
> 
> Best, Lorenzo

Thanks to your reply!
